kind: Template
apiVersion: v1
metadata:
  name: core
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: core
  type: Opaque
  data:
    db.host: ZGI=
    db.port: NTQzMg==
    db.user: cG9zdGdyZXM=
    db.password: bXlzZWNyZXRwYXNzd29yZA==
    keycloak.realm: ZmFicmljOAo=
    keycloak.secret: Cg==
    token.publickey: Cg==
    tenantsvc.url: aHR0cDovL2Y4dGVuYW50Ojgw
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: core
  type: Opaque
  data:
    postgres.sslmode: require
    postgres.connection.maxidle: "90"
    postgres.connection.maxopen: "90"
    chestarter.url: http://che-starter:10000
    notification.serviceurl: ""
    auth.serviceurl: https://auth.openshift.io
    redirect.valid: ".*"
    openshift.tenant.masterurl: https://openshift.local/
    auth_notapproved_redirect: ""
    feature.workitem.remote: "false"
